name: Deploy AWS Lambdas and Layers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - createPaymentSession
          - preflightCORSHandler
          - cognitoUserSync
          - handleStripeWebhook
          - webSocketConnectHandler
          - messageRouterHandler
          - openAIHandler
          - perplexityHandler
          - getChatHistory
        layer:
          - openAILayer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # For deploying Lambda functions
      - name: Install dependencies for Lambda functions
        if: ${{ matrix.function }}
        run: |
          cd lambdas/${{ matrix.function }}
          npm install

      - name: Zip the Lambda function
        if: ${{ matrix.function }}
        run: |
          cd lambdas/${{ matrix.function }}
          zip -r ../../${{ matrix.function }}.zip .

      # For deploying Lambda layers
      - name: Prepare Lambda layer zip
        if: ${{ matrix.layer }}
        run: |
          cd layers/${{ matrix.layer }}
          zip -r ../../${{ matrix.layer }}.zip .

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda function to AWS
        if: ${{ matrix.function }}
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.function }} \
            --zip-file fileb://${{ matrix.function }}.zip \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda layer to AWS
        if: ${{ matrix.layer }}
        run: |
          aws lambda publish-layer-version \
            --layer-name ${{ matrix.layer }} \
            --zip-file fileb://${{ matrix.layer }}.zip \
            --region ${{ secrets.AWS_REGION }}
